---

- hosts: "all"
  become: true
  roles:
   - setup_docker
  
- hosts: "db"
  become: true
  roles:
   - setup_mongodb_container

- hosts: "api"
  become: true
  roles:
   - deploy_backend

- hosts: "client"
  become: true
  roles:
   - deploy_frontend
  