apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
      - name: yolo-backend
        image: jameskimanimoringa/yolo-backend:v1.0.1
        env:
          - name: MONGODB_URI
            value: 'mongodb://mongo-service.default.svc.cluster.local:27017/yolodb?authSource=admin'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
